### ISSUE TITLE
Kanban Board Set-up

### ISSUE THREAD

**Issue by Kgomotso196** [Kgomotso196/Recipe#11]
This project has two assignees:
1. @akezeth 
2. @Kgomotso196

Here's the link to the [project](https://github.com/users/Kgomotso196/projects/2)

**Comment by tugsem** [comment]
##  STATUS: REQUIRED CHANGES ♻️
Hello team👋 , 

Good job so far! 👏 
There are some issues that you still need to work on to go to the next project but you are almost there!

![ Alt Text](https://media.giphy.com/media/l0MYC5rnAHehkVKRq/giphy.gif)
## Highlights 🚀 
✔️kanban created
✔️all cards assigned to the team members
## Required Changes ♻️

- [ ] Please add one more column 'In Review'  as per the requirement.
- [ ] Please add more cards for these requirements:,
- add login and registration pages
- Recipes list:
  Should display a list of recipes created by the logged-in user as in the wireframe.
  Should lead to recipe details.
  If the user is the owner of the recipe, should allow the user to delete it.
- Recipe details:
  Should display a toggle button that allows for a recipe to be made public or private.
  If the recipe is public or the user is the owner of the recipe, should display the recipe details as in the wireframe.
  If the user is the owner of the recipe, should lead to the form that allows the user to add new food.
- Make sure there are no N+1 queries happening.
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Kgomotso196** [comment]
@tugsem Thank you for your kind feedback.Done.

**Comment by gemmen29** [comment]
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 💯 
- Descriptive info ✔️ 

![](https://media.giphy.com/media/mCIjCgs3nWQWfJZvPA/giphy-downsized-large.gif)

## Optional suggestions

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
